FROM python:3.10-slim

RUN python3 -m venv /opt/venv

# Install dependencies:
COPY python_monitoring_requirements.txt .
RUN . /opt/venv/bin/activate && pip install -r python_monitoring_requirements.txt

# Run the application:
COPY monitoring/drift_monitoring.py .