FROM python:3.10-slim

RUN python3 -m venv /opt/venv

# Install dependencies:
COPY python_train_requirements.txt .
RUN . /opt/venv/bin/activate && pip install -r python_train_requirements.txt

# Run the application:
COPY training/train.py .